#!/usr/bin/env sh
set -e
mkdir -p /tmp/build/windows
#!/usr/bin/env bash
trap 'rm -f ./mod.7z; exit 0' TERM
godot-newest --headless --path . --export-release "Windows Desktop" /tmp/build/windows/vex++.exe >/dev/null || {
  echo "fail exit"
  exit 1
}
test -f /tmp/build/windows/vex++.exe || {
  echo "fail exit"
  exit 1
}
7zz a -mx9 -md64m /tmp/build/windows.zip vex++.exe vex++.pck vex++.console.exe

echo /tmp/build/windows.zip

while :; do
  sleep 1
done
