#!/usr/bin/env sh
set -e
mkdir -p /tmp/build/linux
#!/usr/bin/env bash
trap 'rm -f ./mod.7z; exit 0' TERM
godot-newest --headless --path . --export-release "Linux" /tmp/build/linux/vex++.x86_64 >/dev/null || {
  echo "fail exit"
  exit 1
}
test -f /tmp/build/linux/vex++.x86_64 || {
  echo "fail exit"
  exit 1
}
7zz a -mx9 -md64m /tmp/build/linux.zip vex++.x86_64 vex++.pck vex++.sh

echo /tmp/build/linux.zip

while :; do
  sleep 1
done

