#!/usr/bin/env bash
set -e
mkdir -p /tmp/build/windows
trap 'rm -f /tmp/build/windows.zip; rm -fr /tmp/build/windows; exit 0' TERM
godot-newest --headless --path . --export-debug "Windows Desktop" /tmp/build/windows/vex++.exe >/dev/null || {
  echo "fail exit"
  exit 1
}
test -f /tmp/build/windows/vex++.exe || {
  echo "fail exit"
  exit 1
}
7zz a -mx9 -md64m /tmp/build/windows.zip /tmp/build/windows/vex++.exe /tmp/build/windows/vex++.pck /tmp/build/windows/vex++.console.exe

echo /tmp/build/windows.zip

while :; do
  sleep 1
done
