#!/usr/bin/env bash
set -e
mkdir -p /tmp/build/linux
trap 'rm -f /tmp/build/linux.zip; rm -fr /tmp/build/linux; exit 0' TERM
godot-newest --headless --path . --export-debug "Linux" /tmp/build/linux/vex++.x86_64 >/dev/null || {
  echo "fail exit"
  exit 1
}
test -f /tmp/build/linux/vex++.x86_64 || {
  echo "fail exit"
  exit 1
}
7zz a -mx9 /tmp/build/linux.zip /tmp/build/linux/vex++.x86_64 /tmp/build/linux/vex++.pck /tmp/build/linux/vex++.sh >/dev/null

echo /tmp/build/linux.zip

while :; do
  sleep 1
done

